alias readlink=greadlink

source $(dirname $(readlink -f $BASH_SOURCE))/../common/bashrc

PS1="[$CYAN\u@\h $GREEN\W$YELLOW\$(__git_ps1 \" (%s)\")$OFF]🍄  "

if [ -f /usr/local/opt/nvm/nvm.sh ]; then
	export NVM_DIR="$HOME/.nvm"
	source "/usr/local/opt/nvm/nvm.sh"
fi

if [ -f /usr/local/opt/chruby/share/chruby/chruby.sh ]; then
	source /usr/local/opt/chruby/share/chruby/chruby.sh
	source /usr/local/opt/chruby/share/chruby/auto.sh
	chruby 2.0.0
fi

/usr/libexec/java_home >/dev/null 2>&1
if [ $? -eq 0 ]; then
	export JAVA_HOME="$(/usr/libexec/java_home)"
fi

export PATH=/usr/local/sbin:$PATH
export EDITOR='code -w'

alias ls='ls -G'
alias asmver='mono ~/bin/asmver.exe'
alias away='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'
alias format-json='python -m json.tool'
alias format-xml='xmllint --format -'
alias format-html='tidy -config $HOME/codes/dotfiles/common/tidy_html_indent_config.txt -'
alias urldecode='python -c "import urllib, sys; print urllib.unquote(sys.argv[1] if len(sys.argv) > 1 else sys.stdin.read()[0:-1])"'
alias urlencode='python -c "import urllib, sys; print urllib.quote(  sys.argv[1] if len(sys.argv) > 1 else sys.stdin.read()[0:-1])"'
alias flushdns='sudo killall -HUP mDNSResponder'
